### ISSUE TITLE
Expected input checks

### ISSUE THREAD

**Issue by Torxed** [Torxed/slimHTTP#2]
Would be nice if we checked input against specific lengths etc.
For instance:

```python
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    resposne = client.parse()
  File "/home/torxed/github/slimHTTP/slimhttpd.py", line 97, in parse
    return http_request(self).parse()
  File "/home/torxed/github/slimHTTP/slimhttpd.py", line 243, in parse
    method, header = header.split(b'\r\n',1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Should probably have a sanity check before-hand. Even tho this is never meant to be in a production environment unless it's behind a proper HTTP reverse proxy.

**Comment by Torxed** [comment]
Still an issue..

```python
Traceback (most recent call last):
  File "main.py", line 219, in <module>
    response = client.parse()
  File "/srv/http/customer/backend/slimHTTP/slimhttpd.py", line 101, in parse
    return http_request(self).parse()
  File "/srv/http/customer/backend/slimHTTP/slimhttpd.py", line 346, in parse
    method, header = header.split(b'\r\n',1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Torxed** [comment]
```
Traceback (most recent call last):
  File "obtain.life.py", line 638, in <module>
    response = client.parse()
  File "/srv/http/obtain.life/slimHTTP/slimhttpd.py", line 104, in parse
    return http_request(self).parse()
  File "/srv/http/obtain.life/slimHTTP/slimhttpd.py", line 421, in parse
    response = self.methods[method](request=self, headers=self.headers, payload=self.payload, root=web_root)
  File "/srv/http/obtain.life/slimHTTP/slimhttpd.py", line 332, in GET
    return self.local_file(root=root, path=headers[b'path'], headers=headers, payload=payload)
  File "/srv/http/obtain.life/slimHTTP/slimhttpd.py", line 303, in local_file
    data = get_file(root, path, headers=headers, ignore_read=ignore_read)
  File "/srv/http/obtain.life/slimHTTP/slimhttpd.py", line 215, in get_file
    _, data_range = headers[b'range'].split(b'=',1)
ValueError: not enough values to unpack (expected 2, got 1)
```
